"""Run with a Python environment containing playwright (separate from production)."""
from playwright.sync_api import sync_playwright, expect
from pathlib import Path
import subprocess, re
import io, wave
ROOT=Path(__file__).resolve().parents[1]
out=ROOT/'.local-validation'/'ui'
out.mkdir(parents=True,exist_ok=True)
fixture=subprocess.Popen([str(ROOT/'.venv/bin/python'),'-u',str(ROOT/'tests/browser_fixture.py')],stdout=subprocess.PIPE,text=True)
url=fixture.stdout.readline().strip()
assert url.startswith('http://127.0.0.1:'), 'Fixture failed to start'
try:
    with sync_playwright() as p:
        browser=p.chromium.launch(headless=True,args=['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream'])
        page=browser.new_page(viewport={'width':1440,'height':1000},accept_downloads=True,permissions=['microphone'])
        errors=[]
        page.on('pageerror',lambda error: errors.append(str(error)))
        page.goto(url,wait_until='networkidle')
        for width in (1440,768,390,320):
            page.set_viewport_size({'width':width,'height':1000 if width==1440 else 844})
            assert not page.evaluate('document.documentElement.scrollWidth>innerWidth')
            page.screenshot(path=str(out/('overview-%s.png'%width)),full_page=True)
        page.set_viewport_size({'width':1440,'height':1000})
        page.locator('[data-action="new"]').first.click()
        page.locator('input[name="title"]').fill('Браузер сынағы <script>')
        page.locator('[data-action="source"][data-value="text"]').click()
        page.locator('textarea[name="text"]').fill('Айдана: Есепті ертең жіберіңіз.')
        page.locator('#new-form button[type="submit"]').click()
        expect(page.locator('#review-form')).to_be_visible()
        page.locator('[data-row="0"]').fill('Айдана, есепті ертең жіберіңіз.')
        page.locator('#review-form button[type="submit"]').click()
        page.wait_for_url('**/#protocol/*',timeout=15000)
        expect(page.locator('h1')).to_have_text('Браузер сынағы <script>')
        with page.expect_download() as info:
            page.locator('.detail-actions a[download]').click()
        download=info.value
        download.save_as(str(out/'download.docx'))
        assert (out/'download.docx').read_bytes().startswith(b'PK')
        page.locator('[data-action="edit"]').click()
        page.locator('textarea[name="summary"]').fill('Өзгертілген синтетикалық қорытынды.')
        page.locator('[data-field="owner"]').fill('Әлия')
        page.locator('[data-field="due_date"]').fill('2026-10-01')
        page.locator('input[name="reviewed"]').check()
        page.locator('#edit-form button[type="submit"]').click()
        expect(page.locator('#dialog')).not_to_be_visible()
        expect(page.locator('.summary-text')).to_have_text('Өзгертілген синтетикалық қорытынды.')
        page.reload(wait_until='networkidle')
        expect(page.locator('.summary-text')).to_have_text('Өзгертілген синтетикалық қорытынды.')
        page.locator('a.nav-item[href="#tasks"]').click()
        page.locator('#search').fill('Әлия')
        expect(page.locator('.task-card')).to_have_count(1)
        page.locator('.task-check').click()
        expect(page.locator('.task-check.done')).to_have_count(1)
        page.locator('[data-action="lang"][data-lang="ru"]').click()
        expect(page.locator('h1')).to_have_text('Поручения')
        page.screenshot(path=str(out/'tasks-desktop.png'),full_page=True)
        page.set_viewport_size({'width':390,'height':844})
        page.locator('a.nav-item[href="#overview"]').click()
        page.locator('[data-action="lang"][data-lang="kk"]').click()
        page.locator('[data-action="new"]').first.click()
        page.locator('input[name="title"]').fill('Аудио жолын тексеру')
        page.locator('#record-button').click()
        expect(page.locator('#form-error')).to_be_visible()
        page.locator('[name="consent"]').check()
        page.locator('#record-button').click()
        expect(page.locator('#record-button')).to_have_class('btn btn-secondary recording')
        page.evaluate('window.testStream=state.micStream')
        expect(page.locator('#record-button')).to_contain_text(re.compile(r'00:0[1-9]'))
        page.locator('#record-button').click()
        expect(page.locator('#file-label')).to_contain_text('recording-')
        assert page.evaluate('window.testStream.getTracks().every(t=>t.readyState==="ended")')
        page.locator('[name="consent"]').uncheck()
        wav=io.BytesIO()
        with wave.open(wav,'wb') as stream:
            stream.setnchannels(1);stream.setsampwidth(2);stream.setframerate(16000);stream.writeframes(bytes(16000*2))
        page.locator('#audio-file').set_input_files({'name':'synthetic.wav','mimeType':'audio/wav','buffer':wav.getvalue()})
        page.locator('#new-form button[type="submit"]').click()
        expect(page.locator('#form-error')).to_be_visible()
        page.locator('[name="consent"]').check()
        page.locator('#new-form button[type="submit"]').click()
        expect(page.locator('#review-form')).to_be_visible(timeout=15000)
        page.locator('[data-speaker]').fill('Айдана')
        page.screenshot(path=str(out/'phone-review.png'),full_page=True)
        assert not page.locator('#dialog').evaluate('(el)=>el.scrollWidth>el.clientWidth')
        page.locator('#review-form button[type="submit"]').click()
        page.wait_for_url('**/#protocol/*',timeout=15000)
        expect(page.locator('h1')).to_have_text('Аудио жолын тексеру')
        page.screenshot(path=str(out/'phone-detail.png'),full_page=True)
        assert not page.evaluate('document.documentElement.scrollWidth>innerWidth')
        assert not errors,errors
        print('PASS: text → review → protocol → DOCX download → edit → reload → search → task completion → language → mobile audio consent/upload → speaker review → saved protocol')
        browser.close()
finally:
    fixture.terminate()
    fixture.wait(timeout=10)
